### ISSUE TITLE
BOM descriptor contains wrong artifact names

### ISSUE THREAD

**Issue by bertramn** [dadrus/jpa-unit#36]
Looks like the bom descriptor includes invalid dependencies. Lines [pom.xml#L19](https://github.com/dadrus/jpa-unit/blob/aacb2491affaff3f6f0f6564345206e4c2175d6f/bom/pom.xml#L19) and  [pom.xml#L24](https://github.com/dadrus/jpa-unit/blob/aacb2491affaff3f6f0f6564345206e4c2175d6f/bom/pom.xml#L24) should not be `jpa-unit-junitX` but just `jpa-unitX`.

No artifact found for [jpa-unit-junit4](http://search.maven.org/#search%7Cga%7C1%7Ca%3Ajpa-unit-junit4) but I can spot [jpa-unit4](http://search.maven.org/#search%7Cga%7C1%7Ca%3Ajpa-unit4).

Also note that using maven macro functions `<groupId>${project.groupId}</groupId>` and `<version>${project.version}</version>` in your bom will __not__ always populate these fields with the values of your bom but with values of the importing project. It's a known issue and folks typically generate [their bom](http://search.maven.org/remotecontent?filepath=org/springframework/boot/spring-boot-dependencies/1.5.10.RELEASE/spring-boot-dependencies-1.5.10.RELEASE.pom) without maven macro functions.

**Comment by dadrus** [comment]
Thank you @bertramn for this finding. Blame on me, I forgot to change the name in the bom after renaming the artifacts.

The fix is pretty trivial. What I am however curios about is your note about maven properties I used for `groupdId` and `version` in the bom. To be honest, I've never encountered the issue you're talking about. I also failed to find something related to it via google. Do you know some resources, I can take a closer look at to get more insights into it?

The `groupId` is simple, but `version` could introduce headaches - I would like the `version` for each referenced module in the bom to be updated automatically during the release. But maven-release-plugin does not support this is far as I remember. How would you address this?

**Comment by dadrus** [comment]
solved in #40
